//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsToCustomers
    {
        public int id { get; set; }
        public string idCustomer { get; set; }
        public int idSuppliers { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
