//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suppliers()
        {
            this.ProductsToCustomers = new HashSet<ProductsToCustomers>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<System.DateTime> activity_time { get; set; }
        public int idCategory { get; set; }
        public int idAddress { get; set; }
        public int idservice { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsToCustomers> ProductsToCustomers { get; set; }
        public virtual Service Service { get; set; }
    }
}
